[settings]

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[tools]
bun = "latest"
"cargo:watchexec-cli" = "latest"
# rust = "1.82.0"
elixir = "latest"
elixir-ls = "latest"
erlang = "latest"
go = "latest"
lua-language-server = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
rust = "latest"
"ubi:haskell/ghcup-hs" = "latest"
uv = "latest"
