[settings]

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[tools]
bun = "latest"
# rust = "1.82.0"
elixir = "latest"
elixir-ls = "latest"
go = "latest"
rust = "latest"
"ubi:haskell/ghcup-hs" = "latest"
uv = "latest"
